-- 문의하기 폼 저장 테이블 (submit-form.com 실패 시 Supabase에 백업)
-- Supabase 대시보드 → SQL Editor에서 이 파일 내용을 실행하세요.

CREATE TABLE IF NOT EXISTS public.contact_inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  company text,
  email text,
  phone text,
  industry text,
  message text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.contact_inquiries ENABLE ROW LEVEL SECURITY;

-- 익명(anon) 사용자 INSERT 허용 (문의 폼 제출)
DROP POLICY IF EXISTS "Allow anon insert contact_inquiries" ON public.contact_inquiries;
CREATE POLICY "Allow anon insert contact_inquiries"
  ON public.contact_inquiries FOR INSERT TO anon WITH CHECK (true);

-- 읽기 허용 (관리자/공개 확인용)
DROP POLICY IF EXISTS "Allow public read contact_inquiries" ON public.contact_inquiries;
CREATE POLICY "Allow public read contact_inquiries"
  ON public.contact_inquiries FOR SELECT USING (true);
