-- 영상 미디어 테이블 (media_videos)
-- 앱에서 "Error fetching media videos" 가 나오면, 사용 중인 Supabase 대시보드 → SQL Editor에서 이 파일 내용을 실행하세요.

CREATE TABLE IF NOT EXISTS public.media_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  title_en text,
  description text,
  description_en text,
  url text NOT NULL,
  featured_image text,
  published_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.media_videos ENABLE ROW LEVEL SECURITY;

-- 기존 정책이 있으면 무시하고 생성 (에러 시 해당 정책만 삭제 후 다시 실행)
DROP POLICY IF EXISTS "Allow public read access on media_videos" ON public.media_videos;
CREATE POLICY "Allow public read access on media_videos"
  ON public.media_videos FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow authenticated insert on media_videos" ON public.media_videos;
CREATE POLICY "Allow authenticated insert on media_videos"
  ON public.media_videos FOR INSERT
  TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated update on media_videos" ON public.media_videos;
CREATE POLICY "Allow authenticated update on media_videos"
  ON public.media_videos FOR UPDATE
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow authenticated delete on media_videos" ON public.media_videos;
CREATE POLICY "Allow authenticated delete on media_videos"
  ON public.media_videos FOR DELETE
  TO authenticated
  USING (true);

-- 관리자 대시보드는 앱 세션만 쓰고 Supabase는 anon 키를 쓰므로, anon으로도 INSERT/UPDATE/DELETE 허용
DROP POLICY IF EXISTS "Allow anon insert on media_videos" ON public.media_videos;
CREATE POLICY "Allow anon insert on media_videos"
  ON public.media_videos FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anon update on media_videos" ON public.media_videos;
CREATE POLICY "Allow anon update on media_videos"
  ON public.media_videos FOR UPDATE TO anon USING (true);
DROP POLICY IF EXISTS "Allow anon delete on media_videos" ON public.media_videos;
CREATE POLICY "Allow anon delete on media_videos"
  ON public.media_videos FOR DELETE TO anon USING (true);
